getwd()
setwd("./code")
getwd()
hpiUrl = "http://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_PO_metro.txt"
df = read.csv(hpiUrl, header=T)
df = read.table(hpiUrl, sep="\t", header=T, stringsAsFactors = F)
dfCopy = read.table(file = "clipboard", sep="\t", header=T)
dfCopy = read.table(pipe("pbpaste"), sep="\t", header=F)
install.packages("quantmod")
library("quantmod")
getSymbols("AAPL")
barChart(aapl)
barChart(AAPL)
chartSeries(AAPL, subset='last 14 days')
rm(dfCopy)
rm(AAPL)
head(df, n=10)
tail(df,n=10)
str(df)
colnames(df)
names(df)
rownames(df)
summary(df)
install.packages("psych")
library(psych)
describe(df)
mean(df$index_sa)
mean(df$index_sa, na.rm=T)
median(df$index_sa)
hpi2012 = df[df$yr==2012,]
hpi2012Akron = hpi2012[hpi2012$cbsa==10420,]
hpi12Akron = subset(df, yr==2012 & cbsa==10420, c("qtr","index_nsa","index_sa"))
library(dplyr)
hpi12Akron = df %>%
filter(yr==2012 & cbsa==10420) %>%
select(qtr, index_nsa, index_sa)
plot(hpi12Akron$index_nsa, hpi12Akron$index_sa)
plot(df$index_nsa, df$index_sa)
plot(df$yr, df$index_sa, xlab="Year", ylab="HPI, not seasonally adjusted")
plot(df$yr, df$index_sa, xlab="Year", ylab="HPI, not seasonally adjusted", main="HPI by Year")
plot(df$yr, df$index_sa, xlab="Year", ylab="HPI, not seasonally adjusted", main="HPI by Year", las=1)
install.packages("ggplot2")
library(ggplot2)
qplot(yr, index_sa, data=df)
qplot(yr, index_sa, ylim=c(0,500), data=df)
qplot(yr, index_sa, ylim=c(0,500), data=df, geom="jitter")
ggplot(df, aes(x=yr, y=index_sa)) + geom_point()
ggplot(df, aes(x=yr, y=index_sa)) + geom_line()
ggplot(hpi12Akron, aes(x=qtr, y=index_sa)) + geom_line()
ggplot(hpi2012, aes(x=qtr, y=index_sa)) + geom_line()
barplot(df$index_sa)
barplot(hpi2012$index_sa)
hpi2012q1 = filter(hpi2012, qtr==1)
barplot(hpi2012q1$index_sa)
barplot(hpi2012q1$index_sa, main="HPI in 2012, Q1", names.arg = hpi2012q1$metro_name)
boxplot(df$index_sa)
boxplot(df$yr, df$qtr, df$index_sa)
